### PR TITLE
Feature/ur 508 workspace page

### PR DESCRIPTION
**Pull request by BeatrizDieguez**
- Creation of the workspace page
- Integration of the grid into the workspace page
- [Jira Mockup 508](https://aliasgdpr.atlassian.net/browse/ALIAS-508?atlOrigin=eyJpIjoiOTI5NzU5OWI0NjdlNDU5NTk4ZTQwNDhmM2U1NmQzODUiLCJwIjoiaiJ9)
- **Screenshot**

grid-desktop

### CODE REVIEW

**Comment by BeatrizDieguez** [comment]
MAJ PR after delete icon arrow actions + last col (user name)

**Comment by BeatrizDieguez** [comment]
To test the order-change of the rows, please click sur the arrow icon of the first col (vos fiches de traitement)

**Review by prevostjules — APPROVED** [review]
seems perfect

**Comment by Jabuf** [comment]
Just a little precision @BeatrizDieguez to avoid further confusion. This page is the **dashboard**, everything related to the **workspace** will come later (workspace = organization).

**Pull request merged**
